source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Concept2-SDK_Example', :exclusive => true do
  pod "Concept2-SDK", :path => "../"
end

target 'Concept2-SDK_Tests', :exclusive => true do
  pod "Concept2-SDK", :path => "../"
end
