source 'https://github.com/CocoaPods/Specs.git'

platform :ios, 9.0

use_frameworks!

target 'Concept2-SDK_Example', :exclusive => true do
  pod "Concept2-SDK", :path => "../"
end

target 'Concept2-SDK_Tests', :exclusive => true do
  pod "Concept2-SDK", :path => "../"
end
